<?php /* @var \RetailExpress\SkyLink\Block\Adminhtml\Setup\MagentoAttribute $block */ ?>
<?php

/* @var \RetailExpress\SkyLink\Sdk\Catalogue\Attributes\AttributeCode[] $skyLinkAttributeCodes */
$skyLinkAttributeCodes = $block->getSkyLinkAttributeCodes();

/* @var array[] $magentoAttributesByType */
$magentoAttributesByType = $block->getMagentoAttributesByType();
?>
<h3><?=__('Map SkyLink Attributes to Magento Attributes')?></h3>
<form action="<?php /* @escapeNotVerified */ echo $block->getSaveUrl() ?>" method="post">
    <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>" />
    <table class="data-grid">
        <thead>
            <tr>
                <th class="data-grid-th"><?=__('SkyLink Attribute')?></th>
                <th class="data-grid-th"><?=__('Magento Attribute')?></th>
            </tr>
        </thead>
        <tbody>
            <?php /* @var \Magento\Catalog\Api\Data\ProductAttributeInterface $skyLinkAttributeCode */ ?>
            <?php foreach ($skyLinkAttributeCodes as $skyLinkAttributeCode): ?>
                <?php

                /* @var \Magento\Eav\Api\Data\AttributeInterface|null $selectedAttribute */
                $selectedAttribute = $block->getMagentoAttributeForSkyLinkAttributeCode($skyLinkAttributeCode);
                ?>
                <tr>
                    <td>
                        <?=$block->escapeHtml($skyLinkAttributeCode->getLabel())?>
                    </td>
                    <td>
                        <select name="magento_attribute_mappings[<?php /* @escapeNotVerified */ echo $skyLinkAttributeCode->getValue() ?>]">
                            <?php /* @var \Magento\Catalog\Api\Data\ProductAttributeInterface $magentoAttribute */ ?>
                            <?php foreach ($magentoAttributesByType as $magentoAttributeByType): ?>
                                <optgroup label="<?php /* @escapeNotVerified */ echo $magentoAttributeByType['type']->getLabel() ?>">
                                    <?php foreach ($magentoAttributeByType['attributes'] as $magentoAttribute): ?>
                                        <option
                                            value="<?php /* @escapeNotVerified */ echo $magentoAttribute->getAttributeCode() ?>"
                                            <?php if ($selectedAttribute->getAttributeCode() === $magentoAttribute->getAttributeCode()): ?>
                                                selected
                                            <?php endif ?>
                                        >
                                            <?=$block->escapeHtml($magentoAttribute->getDefaultFrontendLabel())?>
                                        </option>
                                    <?php endforeach ?>
                                </optgroup>

                            <?php endforeach ?>
                        </select>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2">
                    <button type="submit"><?=__('Save Mappings')?></button>
                </td>
            </tr>
        </tfoot>
    </table>
</form>

<br><br><br>
