<?php if ($block->canShow()): ?>
    <div id="eta-button">
        <button id="eta-button-button" class="action eta-button">
            <?=$block->escapeHtml($block->getTitle())?>
        </button>
        <div id="eta-button-response-wrapper" class="eta-button-response-wrapper not-ready">
            <p>
                <?=__('ETA:')?> <span id="eta-button-response-date"></span>
            </p>
            <?php if ($block->hasDisclaimer()): ?>
                <p class="eta-button-disclaimer"><em><?=$block->escapeHtml($block->getDisclaimer())?></em></p>
            <?php endif ?>
        </div>
    </div>

    <script type="text/x-magento-init">
        {
            "#eta-button": {
                "skyLinkEtaButton": {
                    "check_waiting_text": "<?=__('Checking ETA...')?>",
                    "eta_url": "<?=$block->escapeHtml($block->getEtaUrl())?>",
                    "button": "#eta-button-button",
                    "response_wrapper": "#eta-button-response-wrapper",
                    "response_date": "#eta-button-response-date"
                }
            }
        }
    </script>
<?php endif ?>
