<div id="app">
    <button @click="getItems">Refresh</button>
    <p>Last ID {{ since_id }}</p>
    <ul>
        <li v-for="item in items">
            <span>[{{ item.human_level }}]</span>
            <strong>{{ item.message }}</strong>
            <em>{{ item.human_logged_at }}</em>
            <pre>{{ item.context | json }}</pre>
        </li>
    </ul>
</div>

<script type="text/x-magento-init">
    {
        "#app": {
            "skyLinkLogging":{
                "log_viewer_url": "<?=$block->escapeHtml($block->getLogViewerUrl())?>",
                "delay": 0.1
            }
        }
    }
</script>
