<div id="logging" class="logging">

    <div class="logging-header">
        <label for="logging-level"><?=__('Filter Level')?></label>
        <select id="logging-level" v-model="currentLevelFilter">
            <?php

            $i = 0;
            foreach ($block->getHumanLevels() as $humanLevel => $level): ?>
                <option value="<?=$block->escapeHtml($level)?>">
                    <?=$block->escapeHtml($humanLevel)?>
                    <?php if ($i++ > 0): ?>
                        <?=__('(and higher)')?>
                    <?php endif ?>
                </option>
            <?php endforeach ?>
        </select>

        <button class="logging-autoscroll" v-if="autoscroll" @click="toggleAutoscroll">
            <?=__('Disable Autoscroll')?>
        </button>
        <button class="logging-autoscroll" v-else @click="toggleAutoscroll">
            <?=__('Enable Autoscroll')?>
        </button>

        <button class="logging-clear" v-show="filteredLogs.length" @click="clearLogs">
            <?=__('Clear Logs')?>
        </button>
    </div>

    <div v-if="filteredLogs.length" v-cloak>

        <ul class="logs" id="logs">
            <li v-for="log in filteredLogs" :class="getCssClass(log)">
                <p class="log-summary abs-clearfix">
                    <strong class="log-message">{{ log.message }}</strong>
                    <em class="log-date">{{ log.human_logged_at }}</em>
                </p>

                <ul class="log-context">
                    <li v-for="(value, key) in log.context">
                        <span class="log-context-key">{{ key }}</span>: <span class="log-context-value">{{ value }}</span>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="message message-notice notice" v-else v-cloak>
        <?=__('There\'s currently nothing logged... This screen will update automatically as logs roll in.')?>
    </div>

</div>

<script type="text/x-magento-init">
    {
        "#logging": {
            "skyLinkLogging": {
                "log_viewer_url": "<?=$block->escapeHtml($block->getLogViewerUrl())?>",
                "log_clearer_url": "<?=$block->escapeHtml($block->getLogClearerUrl())?>?foo=bar",
                "levels": <?=json_encode($block->getLevels())?>,
                "default_level": <?=$block->getDefaultLevel()?>,
                "update_timeout": 1000,
                "logs": "#logs",
                "logs_to_keep": <?=$block->getLogsToKeep()?>
            }
        }
    }
</script>
