<?php /* @var \RetailExpress\SkyLink\Block\Adminhtml\Setup\MagentoAttributeSet $block */ ?>
<?php

/* @var \Magento\Eav\Api\Data\AttributeSetInterface[] $magentoAttributeSets */
$magentoAttributeSets = $block->getMagentoAttributeSets();

/* @var \RetailExpress\SkyLink\Sdk\Catalogue\Attributes\AttributeOption[] $skyLinkProductTypes */
$skyLinkProductTypes = $block->getSkyLinkProductTypes();
?>
<h3><?=__('Map SkyLink Product Types to Magento Attribute Sets')?></h3>
<form action="<?php /* @escapeNotVerified */ echo $block->getSaveUrl() ?>" method="post">
    <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>" />
    <table class="data-grid">
        <thead>
            <tr>
                <th class="data-grid-th"><?=__('SkyLink Product Type')?></th>
                <th class="data-grid-th"><?=__('Magento Attribute Set')?></th>
            </tr>
        </thead>
        <tbody>
            <?php /* @var \RetailExpress\SkyLink\Sdk\Catalogue\Attributes\AttributeOption $skyLinkProductType */ ?>
            <?php foreach ($skyLinkProductTypes as $skyLinkProductType): ?>
                <?php
                /* @var \Magento\Eav\Api\Data\AttributeSetInterface|null $chosenAttributeSet */
                $chosenAttributeSet = $block->getAttributeSetForProductType($skyLinkProductType);
                ?>
                <tr>
                    <td>
                        <?=$block->escapeHtml($skyLinkProductType->getLabel())?>
                    </td>
                    <td>
                        <?php /* @var \Magento\Eav\Api\Data\AttributeSetInterface $magentoAttributeSet */ ?>
                        <select name="magento_attribute_set_mappings[<?php /* @escapeNotVerified */ echo $skyLinkProductType->getId() ?>]">
                            <?php /* @var \Magento\Eav\Api\Data\AttributeSetInterface $magentoAttributeSet */ ?>
                            <?php foreach ($magentoAttributeSets as $magentoAttributeSet): ?>
                                <option
                                    value="<?php /* @escapeNotVerified */ echo $magentoAttributeSet->getAttributeSetId() ?>"
                                    <?php if ($chosenAttributeSet && $chosenAttributeSet->getAttributeSetId() == $magentoAttributeSet->getId()): ?>
                                        selected
                                    <?php endif ?>
                                >
                                    <?=$block->escapeHtml($magentoAttributeSet->getAttributeSetName())?>
                                </option>
                            <?php endforeach ?>
                        </select>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2">
                    <button type="submit"><?=__('Save Mappings')?></button>
                </td>
            </tr>
        </tfoot>
    </table>
</form>

<br><br><br>
