<?php /** @var \RetailExpress\SkyLink\Block\Adminhtml\Setup\MagentoAttribute $block */ ?>
<?php

/** @var \RetailExpress\SkyLink\Catalogue\Attributes\AttributeCode[] $skyLinkAttributeCodes */
$skyLinkAttributeCodes = $block->getSkyLinkAttributeCodes();

/** @var \Magento\Catalog\Api\Data\ProductAttributeInterface[] $magentoAttributes */
$magentoAttributes = $block->getMagentoAttributes();
?>
<h3><?=__('Map SkyLink Attributes to Magento Attributes')?></h3>
<form action="<?php /* @escapeNotVerified */ echo $block->getSaveUrl() ?>" method="post">
    <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>" />
    <table class="data-grid">
        <thead>
            <tr>
                <th class="data-grid-th"><?=__('SkyLink Attribute')?></th>
                <th class="data-grid-th"><?=__('Magento Attribute')?></th>
            </tr>
        </thead>
        <tbody>
            <?php /** @var \Magento\Catalog\Api\Data\ProductAttributeInterface $skyLinkAttributeCode */ ?>
            <?php foreach ($skyLinkAttributeCodes as $skyLinkAttributeCode): ?>
                <?php

                /** @var \Magento\Eav\Api\Data\AttributeInterface|null $chosenAttribute */
                $chosenAttribute = $block->getMagentoAttributeForSkyLinkAttributeCode($skyLinkAttributeCode);
                ?>
                <tr>
                    <td>
                        <?=$block->escapeHtml($skyLinkAttributeCode->getLabel())?>
                    </td>
                    <td>
                        <select name="magento_attribute_mappings[<?php /* @escapeNotVerified */ echo $skyLinkAttributeCode->getValue() ?>]">
                            <?php /** @var \Magento\Catalog\Api\Data\ProductAttributeInterface $magentoAttribute */ ?>
                            <?php foreach ($magentoAttributes as $magentoAttribute): ?>
                                <option
                                    value="<?php /* @escapeNotVerified */ echo $magentoAttribute->getAttributeCode() ?>"
                                    <?php if (null !== $chosenAttribute && $chosenAttribute->getAttributeCode() === $magentoAttribute->getAttributeCode()): ?>
                                        selected
                                    <?php endif ?>
                                >
                                    <?=$block->escapeHtml($magentoAttribute->getDefaultFrontendLabel())?>
                            <?php endforeach ?>
                        </select>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2">
                    <button type="submit"><?=__('Save Mappings')?></button>
                </td>
            </tr>
        </tfoot>
    </table>
</form>

<br><br><br>

