<h1 class="page-title"><?=__('SkyLink Dev Verification')?></h1>

<?php if ($this->hasGroups()): ?>
    <dl>
        <?php foreach ($this->getSortedGroups() as $group): ?>
            <dt>
                <h2><?=$this->escapeHtml($group->getLocalisedName())?></h2>
            </dt>
            <?php if ($this->hasChecksForGroupWithSlug($group->getSlug())): ?>
                <?php foreach ($this->getSortedChecksForGroupWithSlug($group->getSlug()) as $check): ?>
                    <dd>
                        <h3>
                            <?=$this->escapeHtml($check->getLocalisedName())?>
                            <?php if ($check->passes()): ?>
                                <small><?=__('Passes')?></small>
                            <?php else: ?>
                                <small><?=__('Fails')?></small>
                            <?php endif ?>
                        </h3>
                        <?php if (!$check->passes()): ?>
                            <ul>
                                <?php foreach ($check->getLocalisedErrors() as $error): ?>
                                    <li>
                                        <?=$this->escapeHtml($error)?>
                                    </li>
                                <?php endforeach ?>
                            </ul>
                        <?php endif ?>
                    </dd>
                <?php endforeach ?>
            <?php else: ?>
                <p><?=__('No checks have been created for this group yet.')?></p>
            <?php endif ?>
        <?php endforeach ?>
    </dl>
<?php else: ?>
    <p><?=__('There is no verification data available at this time.')?></p>
<?php endif ?>

